version: "3.3"

services:
  db_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: leon
  
  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8080:8080
  
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: db_mysql
            port: 3306
            user: root
            password: leon
    depends_on:
      - db_mysql

volumes:
  mysql-storage: